filebeat.inputs:

- type: filestream

  enabled: true
  paths:
    - 'path to log folder'
  # processors: 
  #   - decode_csv_fields:
  #       fields: 
  #         message: decoded.csv 
  #       separator: ";"
  #   - extract_array:
  #       field: decoded.csv
  #       mappings:
  #         parsed.attribute1: 0
  #         parsed.attribute2: 1
  #         parsed.attribute3: 2
  #         parsed.attribute4: 3
  #         parsed.attribute5: 4
  #         parsed.attribute6: 5
  #         parsed.attribute7: 6
  #         parsed.attribute8: 7
  #         parsed.attribute9: 8
  #         parsed.attribute10: 9
  #   - drop_fields:
  #       fields: ["decoded"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: ["cloud's kibana instance uri"]
  username: "elastic"
  password: "elasticUserPassword"
  index: "index"

setup:
  template.enabled: false
  ilm.enabled: false

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
