filebeat.inputs:

- type: filestream

  enabled: true
  paths:
    - 'path to log folder'
  processors: 
    - decode_csv_fields:
        fields: 
          message: decoded.csv 
        separator: ";"
    - extract_array:
        field: decoded.csv
        mappings:
          parsed.date: 0
          parsed.location: 1
          parsed.operation: 2
          parsed.version: 3
          parsed.process: 4
          parsed.processId: 5
          parsed.messageType: 6
          parsed.step: 7
          parsed.stepMessage: 8
          parsed.stepId: 9
    - drop_fields:
        fields: ["decoded"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: ["cloud's kibana instance uri"]
  username: "elastic"
  password: "elasticUserPassword"
  index: "index"

setup:
  template.enabled: false
  ilm.enabled: false

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
