filebeat.inputs:

- type: filestream

  enabled: true
  paths:
    - 'path to log folder'
  processors: 
    - script:
        lang: "javascript"
        id: "idScript"
        file: "pathScript"


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: ["cloud's kibana instance uri"]
  username: "elastic"
  password: "elasticUserPassword"
  index: "index"

setup:
  template.enabled: false
  ilm.enabled: false

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
